// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhoce8Bguh7qXj8hHOL7-sWYcp8IBm5a8',
    appId: '1:552527795151:web:b2517b5509b89c74f878ba',
    messagingSenderId: '552527795151',
    projectId: 'platform6-boardpad',
    authDomain: 'platform6-boardpad.firebaseapp.com',
    storageBucket: 'platform6-boardpad.firebasestorage.app',
    measurementId: 'G-6GVPBKJ04T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD__kXozYBf7r8aCiuCgM1nOBTfNPBuJfg',
    appId: '1:552527795151:android:400ae05a5b1edfb7f878ba',
    messagingSenderId: '552527795151',
    projectId: 'platform6-boardpad',
    storageBucket: 'platform6-boardpad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc8pqfbusm70Mhcn3-ealNC_ARsuK7abQ',
    appId: '1:552527795151:ios:e07c9aeb22136f9ff878ba',
    messagingSenderId: '552527795151',
    projectId: 'platform6-boardpad',
    storageBucket: 'platform6-boardpad.firebasestorage.app',
    iosBundleId: 'com.example.boardpad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhoce8Bguh7qXj8hHOL7-sWYcp8IBm5a8',
    appId: '1:552527795151:web:c767020faa3850f2f878ba',
    messagingSenderId: '552527795151',
    projectId: 'platform6-boardpad',
    authDomain: 'platform6-boardpad.firebaseapp.com',
    storageBucket: 'platform6-boardpad.firebasestorage.app',
    measurementId: 'G-K6VKNZH87K',
  );
}
